# Generated by Django 2.1.7 on 2021-03-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_businessinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='added_by',
        ),
    ]
