# Generated by Django 2.1.7 on 2021-03-09 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FindandGo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0005_auto_20210309_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('dated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FindandGo.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='biz_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.BusinessTypes'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
