# Generated by Django 2.1.7 on 2021-03-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20210309_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='added_by',
        ),
    ]
