# Generated by Django 2.1.7 on 2021-03-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_remove_businessinfo_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='passwd',
        ),
    ]
