# Generated by Django 2.1.7 on 2021-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_businessinfo_biz_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
